# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Run ASR model benchmark

on: 
  - push
  - pull_request

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: wav2vec2-large-xlsr-persian-v3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ matrix.path }}/requirements.txt

    - name: Install ffmpeg
      run: sudo apt-get install -y ffmpeg
      
    - name: Run Python script
      run: |
        cd ${{ matrix.path }}
        python main.py
